pypro/aperitivos/urls.py
from django.urls import path

from pypro.aperitivos.views import video, indice

app_name = 'aperitivos'
urlpatterns = [
     path('<slug:slug>', video, name='video'),
     path('', indice, name='indice'),
]

pypro/base/urls.py
from django.urls import path

from pypro.base.views import home

app_name = 'base'
urlpatterns = [
    path('', home, name='home'),
]

pypro/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pypro.base.urls')),
    path('aperitivos/', include('pypro.aperitivos.urls')),
   # path('modulos/', include('pypro.modulos.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(
        path('__debug__/', include(debug_toolbar.urls))
    )

pypro/aperitivos/models.py
from django.db import models
from django.urls import reverse


class Video(models.Model):
    titulo = models.CharField(max_length=32)
    slug = models.SlugField(max_length=32)
    youtube_id = models.CharField(max_length=32)
    creation = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('aperitivos:video', args=(self.slug,))
    def __str__(self):
        return f'Video:{self.titulo}'

pypro/base/models.py
from django.contrib import auth
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.contenttypes.models import ContentType
from django.core.exceptions import PermissionDenied
from django.contrib.auth.models import PermissionsMixin
from django.core.mail import send_mail
from django.db import models
from django.db.models.manager import EmptyManager
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


# from .validators import UnicodeUsernameValidator
class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given email, and password.
        """
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)

    def get_by_natural_key(self, username):
        return super().get_by_natural_key(username.lower())

    @classmethod
    def normalize_email(cls, email):
        email = super().normalize_email(email)
        return email.lower()


class User(AbstractBaseUser, PermissionsMixin):
    """
    App base User class.
    Email and password are required. Other fields are optional.
    """

    first_name = models.CharField(_('first name'), max_length=150, blank=True)
    email = models.EmailField(_('email address'), unique=True)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = '%s' % (self.first_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

    def save(self, *args, **kwargs):
        self.clean()
        super().save(*args, **kwargs)

pypro/aperitivos/views.py
from django.shortcuts import render, get_object_or_404

from pypro.aperitivos.models import Video


def indice(request):
    videos = Video.objects.order_by('creation').all()
    return render(request, 'aperitivos/indice.html', context={'videos': videos})


def video(request, slug):
    video = get_object_or_404(Video, slug=slug)
    return render(request, 'aperitivos/video.html', context={'video': video})

pypro/base/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'base/home.html',)

pypro/aperitivos/templates/aperitivos/indice.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Python Pro - Aperitivos{% endblock title %}
{% block description %}Página com todos vídeos gratuitos{% endblock description %}
{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1 class="mt-4 mt-3">Lista de Vídeos Aperitivos</h1>
                <ol>
                    {% for video in videos %}
                        <li><a href="{{ video.get_absolute_url }}">{{ video.titulo | default:"Faltando Título" }}</a></li>
                    {% empty %}
                        <li>Não foi encontrado nenhum vídeo de aperitivo</li>
                    {% endfor %}
                </ol>
            </div>
        </div>
    </div>
{% endblock body %}

pypro/aperitivos/templates/aperitivos/video.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Python Pro - Aperitivo{% endblock title %}
{% block description %}Página com vídeo gratuito de python{% endblock description %}
{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1 class="mt-4 mt-3">{{ video.titulo | default:"Faltando Título" }}</h1>
                <iframe id="ytplayer" type="text/html" width="640" height="360"
                        src="http://www.youtube.com/embed/M7lc1UVf-VE?autoplay=1&origin={{ video.youtube_id }}"
                        frameborder="0">
                </iframe>
            </div>
        </div>
    </div>
{% endblock body %}

pypro/base/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}Python Pro{% endblock title %}</title>

    <meta name="description" content="{% block description %}Página do curso Python Pro{% endblock description %}">
    <meta name="author" content="Rawston Marinho!">
    <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}"/>
    <link href="{% static 'css/bootstrap.min.css' %}/" rel="stylesheet">
    <link href="{% static 'css/style.css' %}/" rel="stylesheet">
    <script src="{% static 'js/jquery.min.js' %}/"></script>
    <script src="{% static 'js/bootstrap.min.js' %}/"></script>
    <script src="{% static 'js/scripts.js' %}/"></script>

</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="padding-left: 10px">
    <a class="navbar-brand" href="{% url 'base:home' %}">Python Pro</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
        </ul>

    </div>
</nav>

{% block body %}{% endblock body %}

{% include 'base/footer.html' with contato_email='ramalho@python.pro.br' only %}

</body>
</html>

pypro/base/templates/base/footer.html
<footer class="main-footer mt-5  pt-4 text-light">
    <div class="container">
        <div class="raw">
            <div class="col">
                <h3>Entre em Contato</h3>
                <address>
                    +55 12 997-411-854
                    <br/>
                    <a href="mailto:{{contato_email}}" class="text-light">{{contato_email}}</a>
                </address>
            </div>
        </div>
    </div>
    <div class="rights pb-4">
        <div class="container">
            <div class="raw">
                <div class="col">
                    {% now 'Y' %} - Python Pro. Todos direitos reservados.
                </div>
            </div>
        </div>
    </div>
</footer>

pypro/base/templates/base/home.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Python Pro - Home{% endblock title %}
{% block body %}
    <div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="jumbotron">
                <h2>
                    Curso de Python com Luciano Ramalho
                </h2>
                <h4 class="mt-4">Matrículas abertas! Custo R$ 1000,00</h4>
                <!-- INICIO DO BOTAO PAGSEGURO -->
                <a href="https://pag.ae/7XZzCrRjv/button" target="_blank" title="Pagar com PagSeguro">
                    <img src="//assets.pagseguro.com.br/ps-integration-assets/botoes/pagamentos/95x45-pagar-laranja.gif"
                         alt="Pague com PagSeguro - é rápido, grátis e seguro!"/>
                </a>
                <!-- FIM DO BOTAO PAGSEGURO -->

                {#                <h4 class="mt-4">Entre na fila de espera</h4>#}
                {##}
                {#                <form action="https://herokuapp.us5.list-manage.com/subscribe/post?u=49dba791d55be88b239cc1c24&amp;id=1549fd4804"#}
                {#                      method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form"#}
                {#                      class="form-row align-items-center" target="_blank" novalidate>#}
                {#                    <div class="form-row align-items-center">#}
                {#                        <div class="col-auto">#}
                {#                            <label class="sr-only" for="mce-EMAIL">Email</label>#}
                {#                            <input type="email" value="" name="EMAIL" class="form-control required" id="mce-EMAIL"#}
                {#                                   placeholder="exemplo@email.com">#}
                {#                        </div>#}
                {#                        <div class="col-auto">#}
                {#                            <label class="sr-only" for="mce-FNAME">Nome</label>#}
                {#                            <input type="text" value="" name="FNAME" class="form-control" id="mce-FNAME"#}
                {#                                   placeholder="Seu nome">#}
                {#                        </div>#}
                {##}
                {#                        <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->#}
                {#                        <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text"#}
                {#                                                                                                  name="b_49dba791d55be88b239cc1c24_1549fd4804"#}
                {#                                                                                                  tabindex="-1"#}
                {#                                                                                                  value=""></div>#}
                {##}
                {#                        <div class="col-auto">#}
                {#                            <input type="submit" value="Salvar" name="subscribe"#}
                {#                                   id="mc-embedded-subscribe" class="btn btn-primary">#}
                {#                        </div>#}
                {#                    </div>#}
                {#                </form>#}


            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <h5 class="card-header">
                Mais detalhes sobre o instrutor
            </h5>
            <div class="card-body">
                <img src="{% static 'img/luciano.jpg' %}" alt="Foto de Luciano Ramalho"
                     class="img-thumbnail float-lg-start me-3"/>
                Ramalho é sócio e professor na <a href="https://www.python.pro.br">Python Pro</a> e autor do
                Livro <a href="http://shop.oreilly.com/product/0636920032519.do" target="_blank">Python
                Fluente</a>. Foi diretor técnico do Brasil Online, primeiro portal da Abril S/A na Web. Liderou
                times para os portais IDG Now, BOL, UOL, AOL Brasil e outros, usando Python desde 1998. Como
                instrutor, atendeu clientes como Citibank, CPqD, Serpro, Presidência da República, Globo.com e
                Itaú. Palestrante em eventos internacionais como FISL, PyCon US e OSCON. Ajudou a criar a
                Associação Python Brasil e foi seu presidente. É membro da Python Software Foundation e fundador
                do Garoa Hacker Clube, o primeiro hackerspace do Brasil.
                </p>
            </div>
        </div>
    </div>
</div>
{% endblock body %}